DROP VIEW public.cafe_with_ratings;
ALTER TABLE public.cafes ALTER COLUMN search_vector TYPE tsvector USING search_vector::tsvector;
CREATE INDEX idx_cafes_search ON public.cafes USING gin (search_vector);
CREATE VIEW public.cafe_with_ratings AS SELECT c.id,
     c.created_at,
     c.updated_at,
     c.is_published,
     c.is_claimed,
     c.membership_tier,
     c.featured_until,
     c.owner_ids,
     c.contributor_id,
     c.name,
     c.slug,
     c.description,
     c.thumbnail,
     c.gallery,
     c.region,
     c.province,
     c.city_municipality,
     c.address_display,
     c.lat,
     c.lng,
     c.has_wifi,
     c.has_sockets,
     c.has_parking,
     c.has_aircon,
     c.is_pet_friendly,
     c.has_outdoor_seating,
     c.is_work_friendly,
     c.roaster,
     c.brew_methods,
     c.price_level,
     c.is_verified,
     c.is_active,
     c.search_vector,
     COALESCE(s.average_rating, 0::numeric::real) AS average_rating,
     COALESCE(s.total_reviews, 0) AS total_reviews,
     COALESCE(s.rating_distribution, '{"1": 0, "2": 0, "3": 0, "4": 0, "5": 0}'::jsonb) AS rating_distribution
    FROM public.cafes c
      LEFT JOIN public.cafe_rating_stats s ON c.id = s.cafe_id;
