import { Cafe } from "../types/cafe";

export const dummyCafes: Cafe[] = [
    {
        id: crypto.randomUUID(),
        created_at: new Date(),
        name: "Strange Matcha",
        slug: "strange-matcha",
        description: "Strange Matcha is a unique and trendy cafe that offers a unique experience for coffee lovers. The cafe is located in the heart of Cebu and is known for its unique and creative approach to coffee.",
        thumbnail: "/strange-matcha.jpg",
        gallery: ["/strange-matcha.jpg", "/strange-matcha.jpg", "/strange-matcha.jpg"],
        address_display: "Molave Community Marketplace, Molave St, Cebu City",
        lat: 10.3167,
        lng: 123.9000,
        area: "Cebu City",
        has_wifi: true,
        has_sockets: true,
        has_parking: true,
        price_level: 1,
        payment_methods: ["cash", "card", "gcash"],
        raoster: "Grounds",
        rating: 4.5,
        reviews: 10,
        is_verified: true,
    },
    {
        id: crypto.randomUUID(),
        created_at: new Date(),
        name: "Bo's Coffee Casa Gorordo",
        slug: "bos-coffee-casa-gorordo",
        description: "Enjoy coffee in the 1850s ambiance of Casa Gorordo Museum. Bo's Coffee is a proudly Cebuano coffee chain that serves locally-sourced Filipino coffee beans.",
        thumbnail: "/bos-coffee.jpg",
        gallery: ["/bos-coffee.jpg"],
        address_display: "35 Eduardo Aboitiz St, Parian, Cebu City",
        lat: 10.2999,
        lng: 123.9049,
        area: "Cebu City",
        has_wifi: true,
        has_sockets: true,
        has_parking: false,
        price_level: 2,
        payment_methods: ["cash", "card", "gcash"],
        raoster: "Bo's Coffee",
        rating: 4.8,
        reviews: 24,
        is_verified: true,
    }
]